name: Build Python

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-python.yml'
      - 'wrappers/**'
      - 'src/**'
      - 'include/**'
      - 'src/cli/**'
      - 'data/**'
      - 'models/**'
      - 'voices/**'
      - 'CMakeLists.txt'

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit

  build-macos:
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit

  build-windows:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  build-python:
    needs:
        - build-linux
        - build-windows
        - build-macos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download Linux Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64
          path: linux

      - name: Download Windows Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-x86_64
          path: windows

      - name: Download macOS ARM64 Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64
          path: macos

      - name: Create Build Directories
        run: |
            mkdir -p build/linux/bin/lib
            mkdir -p build/windows/bin/lib
            mkdir -p build/macos/bin/lib
            mkdir -p build/data
            mkdir -p build/models
            mkdir -p build/voices

      - name: Copy Linux Build Artifacts
        run: |
            cp -r linux/include build/linux/
            cp linux/bin/babylon build/linux/bin/
            cp -r linux/bin/lib/* build/linux/bin/lib/

      - name: Copy Windows Build Artifacts
        run: |
            cp -r windows/include build/windows/
            cp windows/bin/babylon.exe build/windows/bin/
            cp -r windows/bin/lib/* build/windows/bin/lib/

      - name: Copy macOS ARM64 Build Artifacts
        run: |
            cp -r macos/include build/macos/
            cp macos/bin/babylon build/macos/bin/
            cp -r macos/bin/lib/* build/macos/bin/lib/

      - name: Copy Shared Data Assets
        run: cp -r data/* build/data

      - name: Copy Shared Model Assets
        run: cp -r models/* build/models

      - name: Copy Shared Voice Assets
        run: cp -r voices/* build/voices

      - name: Copy Python Wrapper
        run: cp wrappers/babylon.py build/__init__.py

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: python
            path: build/
